[package]
name = "buffer"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
safety_check = []

[dependencies]
sdl2.workspace = true
